version: "3.1"
services:

    redis:
        image: redis:alpine
        container_name: caffee-redis

    webserver:
        image: nginx:alpine
        container_name: caffee-webserver
        working_dir: /application
        volumes:
            - .:/application
            - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
        ports:
            - "1055:80"

    php-fpm:
        build: docker/php-fpm
        container_name: caffee-php-fpm
        working_dir: /application
        volumes:
            - .:/application
            - ./docker/php-fpm/php-ini-overrides.ini:/etc/php/7.3/fpm/conf.d/99-overrides.ini
